eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8801

spring:
  datasource:
    url: jdbc:mysql://121.41.48.96:3306/adam_xzqa?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: helloServer

mybatis:
  configuration:
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl











