server:
   port: 9000

spring:
  application:
    name: zuulServer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: helloServer
    api-b:
      path: /api-b/**
      serviceId: worldServer
    api-c:
      path: /api-c/**
      serviceId: ribbonServer
    api-d:
      path: /api-d/**
      serviceId: redisServer

