eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8805

spring:
  redis:
    database: 0
    host: 122.112.216.37
    port: 6379
    password:
    timeout:
  application:
    name: redisServer
